import { render, screen } from "@testing-library/react";
import Input from "../Input";

// AUTO-GENERATED by generate-test.ts — DO NOT EDIT
// Add // MANUAL inside the file to prevent overwrites

describe('Input component', () => {
  it('renders without crashing', () => {
    const { container } = render(<Input  />);
    expect(container).toBeDefined();
  });

    describe("label prop", () => {
      it("renders label text", () => {
        render(<Input  label={"Email"} />);
        expect(screen.getByText("Email")).toBeInTheDocument();
      });
    });
    describe("error prop", () => {
      it("renders error text", () => {
        render(<Input  error={"Required"} />);
        expect(screen.getByText("Required")).toBeInTheDocument();
      });
    });
    describe("className prop", () => {
      it("applies custom class", () => {
        const { container } = render(<Input  className="custom-class" />);
        expect(container.firstChild).toHaveClass("custom-class");
      });
    });});
